spring.application.name=auth-service

server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel_auth
spring.datasource.username=postgres

spring.datasource.password=${POSTGRES_PASSWORD}


# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.private.key-path=keys/private_key.pem
jwt.public.key-path=keys/public_key.pem

spring.data.redis.host=localhost
spring.data.redis.port=6381

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always