services:


  postgres:
    image: postgres:16
    container_name: sentinel-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - sentinel-network



  redis:
    image: redis:7
    container_name: sentinel-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sentinel-network


  user-service:
    build:
      context: ./user-service
    container_name: sentinel-user-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sentinel_user
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - sentinel-network

  auth-service:
    build:
      context: ./auth-service
    container_name: sentinel-auth-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sentinel_auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    volumes:
      - ./auth-service/keys:/app/keys:ro
    networks:
      - sentinel-network


  api-gateway:
    build:
      context: ./api-gateway
    container_name: sentinel-api-gateway
    ports:
      - "8080:8080"
    environment:
      USER_SERVICE_URL: http://user-service:8083
      AUTH_SERVICE_URL: http://auth-service:8082
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - sentinel-network




networks:
  sentinel-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: