spring.application.name=api-gateway
server.port=8080

# User Service
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**

# Auth Service
spring.cloud.gateway.server.webflux.routes[1].id=auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/auth/**

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

jwt.public-key-path=keys/public_key.pem